name: Fixed 15 Commits Daily (No Push Trigger)

on:
  schedule:
    - cron: '0 0 * * *' # Har kuni faqat bir marta (O'zbekiston vaqti bilan 05:00 da)
  workflow_dispatch:      # Faqat o'zingiz "Run workflow" tugmasini bossangiz ishlaydi

permissions:
  contents: write

concurrency:
  group: daily-maintenance
  cancel-in-progress: true

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Hard Limit 15 Commits
        run: |
          git config --local user.email "kamolbekrozmamatov@gmail.com"
          git config --local user.name "ruzmamatov99"
          
          for i in {1..15}
          do
            echo "Daily log update: $(date)" > activity_log.txt
            git add activity_log.txt
            git commit -m "System maintainance $i/15"
          done
          
          git push origin main
